apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.19.0
  values:
    image:
      tag: appmesh-up-7d4c3c5
    crd:
      create: false
    metricsServer: http://appmesh-prometheus:9090
    meshProvider: appmesh
