---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUJemZurSsiKFLB0r8umUTg6EgySAwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMjAwMTI3MTExMzAwWhcNMjUwMTI1MTExMzAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOtQqDg4/Q0yM/ye8QR+SsHNufPXe64SR+uaAYRqdeNO7JrXDXUbT5WczqRGn/6i
    aEObnY1/i0rWUqkkFcYkmgmyKfMFsj+xfP5XsO8L+87pXjFlfyWoAgCcSygaEfw4
    1YfNGsN4zVILRuUKhe9JdUzQIdT08ELOg+dQLp51Y04Ezu57ONpNtVzEe+KfQNiD
    +54CEh/KHvgAO+LHNk0Jb5Cisvh6whdLh4Axwzo90Y9Z+UOEROMlz0UupJYv33yw
    yoW91KH87D5gS8/MgoQPCuEDRXxOHRbSR5Tp/qUUla5+Qd1HWWE9GD4GbDdb3IEO
    h8Ai51OlQea4yiG+6IQwuRAAJNLHMkjko+RIuIM4j0gteXIkKAUyn1/zNVPTU/tV
    fGxygJ3NaNcxz2ZYmDxeUex/cuq8N05S2rbstuzBbz1cwXLoRUbMbHXLUaYxxpbu
    P+cs5k5DvEjWRv3sFWI1UViMCNOqLgC2MdYCskyYX6TbGCNxWnpHQsywVO1bW4Cn
    FBBMU7aXJZmNsjNHLThquXaRRwqPf9Z3py0rniFD6u7ZigvqyU3BM9YU0C6geFHV
    n6Il//87Eec6llfd2fTCUhxJq6fGzSmqdOTdZ+ta2pcbJa9nXfOzkrr7iZWO1scE
    GrF0O0XmxLMmXj1JhC3zpNzMRwr3seZMLmjPiShRP5z9AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTXQgeGyErCDkN/
    11jTdhZJYglkWzANBgkqhkiG9w0BAQ0FAAOCAgEApt8I7f0FNFN0pNaAzQl4v9T6
    JiGoydRi9TQ6UQOpnJ9LW7YfGe1MGqRzasHhGaT0VpwCGUKStb54LClGB43GiNbU
    gg7gEzOxuaQ07sZ5xEn+ZkIgMgq2eBg2nvOHXE2M4X+kUD/vL2xGtsvKzg7l0AQm
    12Udsqym+G75I9GlY9MMjrv1E1O9kMgGTDQbqJ3JXQaBCi9pCsEGnsInj+YFPaeN
    Go+dAMbAihxKcmyxfH8QXKslrz738n6jDQW/uAUVLnUpPJlGHhwBJro2zWvwTn2v
    alATfDYm8r7x5BPqu7IVVmiXahVZ/3GL7Kudkn4OT+jL5+COcWzmtnNLKUdZAp5o
    H8dzEsJfaHVdadRWIhIl06vYLRXrQNr8UoRdO11nZKidHbsUr/87c7curYLBb4V9
    jBN/XmAzDBcWRawomUPw/hu+hy9AoYI/7+rAQ2+P4Ddr+iPWXb+hxZucwmY/AgBD
    JHFOdIJOPhl14VUuCHwMcZfi5osck3z44a38BtLCwyP5PwtjuLzC4pwf8bIlmAhB
    J0huRRKb5i3qeGT7ittPtM+g/6TZtbYJSbZ9CjfnCEfv5bH3UD2URqRrpeR2Ob6E
    KvFdtpTp5RUW4+I6Ga88QPATXU94auubzevXxXaSn8TuaDSdD7Fpkax3xmtfZ3rZ
    rkaRfAdBGpOozQcKcCg=
    -----END CERTIFICATE-----
    
