---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUVald2tS1Zr40NBpHtcGJ+3ic6mkwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTA3MTIwMjAwWhcNMjQxMTA1MTIwMjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANFEFn9A0ItTXOqk/nF6GJzv2SspNDOZ+nI0r2asaGgYqMGL8TkMxXD4aWLqVPBD
    qKfZnsHj8egGR8AFnyl4aTGNWRVojkIaKc1HdFe5Hj2HXPlzoSOLMQ6lh6gBlL6p
    kZnC+IsBIrGpLZmlep/xluv/aqtSWjeT0KN9nt07XHeqBcgNQHkxkChytB8Q0lgl
    mlkGPV6tMUAY0vGrorxyTDJj3PoT7f16fVpSP1akA3NYh6+BSz7YAM8kkaFJQ/+0
    P7NyR5uIzFr8bmG+1bXOX/zH/wUKA4U/L/f6Q1oB8hHvF8p2rR5m6znVz0FSpGnD
    K5XP3cgCyGiuRcMoBklJ8+CPQ/inScBS/LI6KKWzsrh5STx9dfxYU7LBv2C/HEyi
    anc4yfdITH0BiSe4btfbTWk5E47nvIhn0ZwU9MfF83vmrnJmd5l5/SMIWwiGCyab
    wD7B5nuyvyja6B7nZUjrecEaQabTFnx2wcGlkfmYqGHcN2UqkYbCPoLrNpoJdPrp
    w4mblCbmHDKLC+sXNdEmz6UwIsgpofnaq/fWjcLmyfpJuG3h09XC1Xvk3jiSsnLD
    vHd5F9Vb1P9C/qXkcdprkB2VTdfK1eD+xoXK9+kxausXzKeeWL9s48Yzh6jGMJgv
    ZB6XAVSe3lDtSDae85i+8OtrLNr36PfFhXTsdmsuOVRtAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSqiBddC/Ye1gwK
    ZN3cQj1USWMK+TANBgkqhkiG9w0BAQ0FAAOCAgEAQkdPudwfmnHs0+6rF+cQU2nP
    nO6BMQxEHC118AyIGiFa/xKiNdeGiV2JsgDaYvV8in8mx8j0UU4vh7gPa1/IrunJ
    XuWgnrIrI5ziqRR9EK+2/rIexgmECId+nRt74oHFXa6NNOV6epiXpEOdW/By4g/K
    3cLJG1ZZDbrbysdWUmkT2mGxweh+/F/T+N8IUWV6bRxwiGO5Zu4iTe/paqkIWG/g
    6BwMkpiji2CEQ3BBmsckvLSL8/c9TY0LfTO39MaZ48eot/yT/kpT0/J9PLs2qmaC
    Vv3V0j4Fulq+ERVF8O5SoNg7vhVYt3TF1DeiTpvCLnV7nu4NdV0O1AaBFZrB4nbQ
    mHl6TcewxMvJ6atYBu0mwe37bwcQUfE3IYV/gCwbSRXf+O+A+XSr1OegX3zSPX5c
    bPqQ3FBiqLRvbTcUIqhuKGaHHLen/d00FZxGDEz6nVgSb4NOWmSBoQ8mxNGFBclS
    qkThAmWQHhGd0JwQu6EiopGvAbAP9YqcdJz7rjQlBC1yjhCPOMtntXsRE03FxvTs
    5CBciQ4CRyKiv5cxx8Kf7BXvgui0jwwtLZYzv09bRLUJhT4P1LCj9tEoWRHYdQyE
    FWfhuJ2SLX5s20W6oAAxJuZEKRNxk6C0H58LgFKZAGxMlViPZAkJZFx5wkJ1AGFK
    Kc/ibDa9Mc3M4pExv7U=
    -----END CERTIFICATE-----
    
