accessLogger:
  enabled: false
  image:
    repository: access-logger
  port: 8083
  replicas: 1
  resources: null
  serviceName: AccessLog
crds:
  create: true
discovery:
  deployment:
    floatingUserId: false
    image:
      repository: discovery
      tag: 0.20.8
    replicas: 1
    resources: null
    runAsUser: 10101
    stats: true
  enabled: true
  fdsMode: ""
gateway:
  certGenJob:
    image:
      repository: certgen
    restartPolicy: OnFailure
  conversionJob:
    image:
      repository: gateway-conversion
    restartPolicy: Never
  deployment:
    floatingUserId: false
    image:
      repository: gateway
    replicas: 1
    resources: null
    runAsUser: 10101
    stats: true
  enabled: false
  proxyServiceAccount:
    disableAutomount: false
  updateValues: false
  upgrade: false
  validation:
    alwaysAcceptResources: true
    failurePolicy: Ignore
    secretName: gateway-validation-certs
gatewayProxies:
  gatewayProxyV2:
    configMap:
      data: null
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        antiAffinity: false
        replicas: 1
        resources: null
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
      image:
        repository: gloo-envoy-wrapper
      probes: false
      resources: null
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
    stats: true
global:
  glooRbac:
    Namespaced: false
    create: true
  image:
    pullPolicy: IfNotPresent
    registry: quay.io/solo-io
gloo:
  deployment:
    floatingUserId: false
    image:
      repository: gloo
      tag: 0.20.8
    replicas: 1
    resources: null
    runAsUser: 10101
    stats: true
    validationPort: 9988
    xdsPort: 9977
ingress:
  deployment:
    image:
      repository: ingress
      tag: 0.20.8
    replicas: 1
    resources: null
  enabled: true
  requireIngressClass: null
ingressProxy:
  configMap: {}
  deployment:
    httpPort: 80
    httpsPort: 443
    image:
      repository: gloo-envoy-wrapper
      tag: 0.20.8
    replicas: 1
    resources: null
k8s:
  clusterName: cluster.local
namespace:
  create: false
settings:
  create: true
  integrations:
    knative:
      enabled: false
      version: null
  singleNamespace: false
